// <auto-generated />
namespace AppEjemploLayout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d_20112016_1034 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d_20112016_1034));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201537393_d_20.11.2016_10.34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
