// <auto-generated />
namespace AppEjemploLayout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _7_12_2016_4_58 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_7_12_2016_4_58));
        
        string IMigrationMetadata.Id
        {
            get { return "201612072159024_7_12_2016_4_58"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
